In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import os
from google.colab import drive

# 1. Montage du Drive
drive.mount('/content/drive')

# 2. Définition des chemins (Basé sur ta capture)
path = "/content/drive/MyDrive/pfe_digital_twin"

# 3. Chargement des données (Lecture des fichiers Excel de ta capture)
# Note : Si tes fichiers sont des .xlsx, on utilise read_excel
df_clinical = pd.read_excel(f"{path}/EGFR_Mutations_Table7_Cleaned.xlsx")
df_rppa = pd.read_excel(f"{path}/S_Table_13_RPPA.xlsx", header=1) # On saute l'en-tête décoratif
df_copy = pd.read_excel(f"{path}/S_Table_6_Copy_Number.xlsx", header=1)

# 4. Nettoyage rapide
for df in [df_clinical, df_rppa, df_copy]:
    df.columns = df.columns.str.strip()

# --- DEBUGGING: Print columns to identify the issue ---
print("df_clinical columns:", df_clinical.columns.tolist())
print("df_rppa columns:", df_rppa.columns.tolist())
print("df_copy columns:", df_copy.columns.tolist())
print("\n-- df_rppa head --")
print(df_rppa.head())
print("\n-- df_copy head --")
print(df_copy.head())
# ------------------------------------------------------

# 5. Fusion "Master"
# The merge operations are commented out because 'Tumor ID' is not found in df_rppa or df_copy.
# You need to identify the correct common column(s) for merging these dataframes.
# Also, df_copy's column names suggest a loading issue that needs to be resolved first.
# master = pd.merge(df_clinical, df_rppa, on='Tumor ID', how='inner')
# master = pd.merge(master, df_copy, on='Tumor ID', how='inner')

# Placeholder for master to avoid errors in subsequent (commented) lines
master = pd.DataFrame()

# 6. Sauvegarde du Graal (commented out as master is not yet fully merged)
# master.to_csv(f"{path}/Master_Twin_Data.csv", index=False)

# print(f"🚀 Succès ! Ton Jumeau Numérique possède désormais {master.shape[0]} patients avec toutes leurs données fusionnées.")
print("\nMerge operations halted due to missing 'Tumor ID' in some dataframes and potential loading issues with df_copy.")
print("Please provide more information on the structure of S_Table_13_RPPA.xlsx and S_Table_6_Copy_Number.xlsx")
print("and how they are intended to be joined with the clinical data.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
df_clinical columns: ['Tumor ID', 'Sex', 'Age at diagnosis', 'T stage', 'N stage', 'Tumor stage', 'Smoking Status', 'Survival', 'Transversion High/Low', 'Nonsilent Mutations', 'Nonsilent Mutations per Mb', 'Oncogene Negative or Positive Groups', 'TP53', 'STK11', 'KRAS', 'KEAP1', 'EGFR', 'RBM10', 'SMARCA4', 'ARID1A', 'CDKN2A', 'U2AF1', 'SETD2', 'BRAF', 'RB1', 'PIK3CA', 'MGA', 'NF1', 'MET', 'ERBB2', 'HRAS', 'NRAS', 'AKT1', 'RIT1', 'MAP2K1', 'Fusions mentioned in main text only', 'expression_subtype', 'NA=not applicable', 'TP53_2', 'KRAS_2', 'EGFR_2', 'STK11_2', 'RBM10_2', 'CDKN2A_2', 'KEAP1_2', 'BRAF_2', 'U2AF1_2', 'SMARCA4_2', 'NF1_2', 'MET_2', 'ARID1A_2', 'SETD2_2', 'RB1_2', 'PIK3CA_2', 'MGA_2', 'RIT1_2', 'NKX2-1', 'MDM2', 'TERT', 'TERC', 'MYC', 'CCND1', 'CCNE1', 'CDK4', 'ERBB2_2', 'HRAS_2', 'NRAS_2', 'AKT1_2', 'TP53_3', 'KRAS_3', 'EGFR_3', 'STK11_3', 'RBM10_3', 'CDKN2A_3', 'KEAP1_3', 'BRAF_3', 'U2AF1_3', 'SMARCA4_3', 'NF1_3', 'MET_3', 'ARID1A_3', 'SETD2_3', 'RB1_3', 'PIK3CA_3', 'MGA_3', 'RIT1_3', 'NKX2-1_2', 'MDM2_2', 'TERT_2', 'TERC_2', 'MYC_2', 'CCND1_2', 'CCNE1_2', 'CDK4_2', 'ERBB2_3', 'HRAS_3', 'NRAS_3', 'AKT1_3', 'iCLUSTER output', 'methylation signature', 'mechanism of mTOR pathway activation', 'ABSOLUTE calls', 'ABSOLUTE calls_2']
df_rppa columns: ['Protein Name', 'Gene Name', 'Antibody validation status', 'Antibody Origin', 'Antibody Source (Company)', 'Catalog Number']
df_copy columns: [';', ';.1', ';.2', ';.3', ';.4', ';.5', ';.6', ';.7', ';.8', ';.9', ';.10', ';.11', ';.12', ';.13', ';.14', ';.15', ';.16', ';.17', ';.18', ';.19', ';.20', ';.21', ';.22', ';.23', ';.24', ';.25', ';.26', ';.27', ';.28', ';.29', ';.30', ';.31', ';.32', ';.33', ';.34', ';.35', ';.36', ';.37', ';.38', ';.39', ';.40', ';.41', ';.42', ';.43', ';.44', ';.45', ';.46', ';.47', ';.48', ';.49', ';.50', ';.51', ';.52', ';.53', ';.54', ';.55', ';.56', ';.57', ';.58', ';.59', ';.60', ';.61', ';.62', ';.63', ';.64', ';.65', ';.66', ';.67', ';.68', ';.69', ';.70', ';.71', ';.72', ';.73', ';.74', ';.75', ';.76', ';.77', ';.78', ';.79', ';.80', ';.81', ';.82', ';.83', ';.84', ';.85', ';.86', ';.87', ';.88', ';.89', ';.90', ';.91', ';.92', ';.93', ';.94', ';.95', ';.96', ';.97', ';.98', ';.99', ';.100', ';.101', ';.102', ';.103', ';.104', ';.105', ';.106', ';.107', ';.108', ';.109', ';.110', ';.111', ';.112', ';.113', ';.114', ';.115', ';.116', ';.117', ';.118', ';.119', ';.120', ';.121', ';.122', ';.123', ';.124', ';.125', ';.126', ';.127', ';.128', ';.129', ';.130', ';.131', ';.132', ';.133', ';.134', ';.135', ';.136', ';.137', ';.138', ';.139', ';.140', ';.141', ';.142', ';.143', ';.144', ';.145', ';.146', ';.147', ';.148', ';.149', ';.150', ';.151', ';.152', ';.153', ';.154', ';.155', ';.156', ';.157', ';.158', ';.159', ';.160', ';.161', ';.162', ';.163', ';.164', ';.165', ';.166', ';.167', ';.168', ';.169', ';.170', ';.171', ';.172', ';.173', ';.174', ';.175', ';.176', ';.177', ';.178', ';.179', ';.180', ';.181', ';.182', ';.183', ';.184', ';.185', ';.186', ';.187', ';.188', ';.189', ';.190', ';.191', ';.192', ';.193', ';.194', ';.195', ';.196', ';.197', ';.198', ';.199', ';.200', ';.201', ';.202', ';.203', ';.204', ';.205', ';.206', ';.207', ';.208', ';.209', ';.210', ';.211', ';.212', ';.213', ';.214', ';.215', ';.216', ';.217', ';.218', ';.219', ';.220', ';.221', ';.222', ';.223', ';.224', ';.225', ';.226', ';.227', ';.228', ';.229', ';.230', ';.231', ';.232', ';.233', ';.234', ';.235', ';.236', ';.237', ';.238', ';.239', ';.240', ';.241', ';.242', ';.243', ';.244', ';.245', ';.246', ';.247', ';.248', ';.249', ';.250', ';.251', ';.252', ';.253', ';.254', ';.255', ';.256', ';.257', ';.258', ';.259', ';.260', ';.261', ';.262', ';.263', ';.264', ';.265', ';.266', ';.267', ';.268', ';.269', ';.270', ';.271', ';.272', ';.273', ';.274', ';.275', ';.276', ';.277', ';.278', ';.279', ';.280', ';.281', ';.282', ';.283', ';.284', ';.285', ';.286', ';.287', ';.288', ';.289', ';.290', ';.291', ';.292', ';.293', ';.294', ';.295', ';.296', ';.297', ';.298', ';.299', ';.300', ';.301', ';.302', ';.303', ';.304', ';.305', ';.306', ';.307', ';.308', ';.309', ';.310', ';.311', ';.312', ';.313', ';.314', ';.315', ';.316', ';.317', ';.318', ';.319', ';.320', ';.321', ';.322', ';.323', ';.324', ';.325', ';.326', ';.327', ';.328', ';.329', ';.330', ';.331', ';.332', ';.333', ';.334', ';.335', ';.336', ';.337', ';.338', ';.339', ';.340', ';.341', ';.342', ';.343', ';.344', ';.345', ';.346', ';.347', ';.348', ';.349', ';.350', ';.351', ';.352', ';.353', ';.354', ';.355', ';.356', ';.357', ';.358', ';.359', ';.360', ';.361', ';.362', ';.363', ';.364', ';.365', ';.366', ';.367', ';.368', ';.369', ';.370', ';.371', ';.372', ';.373', ';.374', ';.375', ';.376', ';.377', ';.378', ';.379', ';.380', ';.381', ';.382', ';.383', ';.384', ';.385', ';.386', ';.387', ';.388', ';.389', ';.390', ';.391', ';.392', ';.393', ';.394', ';.395', ';.396', ';.397', ';.398', ';.399', ';.400', ';.401', ';.402', ';.403', ';.404', ';.405', ';.406', ';.407', ';.408', ';.409', ';.410', ';.411', ';.412', ';.413', ';.414', ';.415', ';.416', ';.417', ';.418', ';.419', ';.420', ';.421', ';.422', ';.423', ';.424', ';.425', ';.426', ';.427', ';.428', ';.429', ';.430', ';.431', ';.432', ';.433', ';.434', ';.435', ';.436', ';.437', ';.438', ';.439', ';.440', ';.441', ';.442', ';.443', ';.444', ';.445', ';.446', ';.447', ';.448', ';.449', ';.450', ';.451', ';.452', ';.453', ';.454', ';.455', ';.456', ';.457', ';.458', ';.459', ';.460', ';.461', ';.462', ';.463', ';.464', ';.465', ';.466', ';.467', ';.468', ';.469', ';.470', ';.471', ';.472', ';.473', ';.474', ';.475', ';.476', ';.477', ';.478', ';.479', ';.480', ';.481', ';.482', ';.483', ';.484', ';.485', ';.486', ';.487', ';.488', ';.489', ';.490', ';.491', ';.492', ';.493', ';.494', ';.495', ';.496', ';.497', ';.498', ';.499', ';.500', ';.501', ';.502', ';.503', ';.504', ';.505', ';.506', ';.507', ';.508', ';.509', ';.510', ';.511', ';.512', ';.513', ';.514', ';.515', ';.516', ';.517', ';.518', ';.519', ';.520', ';.521', ';.522', ';.523', ';.524', ';.525', ';.526', ';.527', ';.528', ';.529', ';.530', ';.531', ';.532', ';.533', ';.534', ';.535', ';.536', ';.537', ';.538', ';.539', ';.540', ';.541', ';.542', ';.543', ';.544', ';.545', ';.546', ';.547', ';.548', ';.549', ';.550', ';.551', ';.552', ';.553', ';.554', ';.555', ';.556', ';.557', ';.558', ';.559', ';.560', ';.561', ';.562', ';.563', ';.564', ';.565', ';.566', ';.567', ';.568', ';.569', ';.570', ';.571', ';.572', ';.573', ';.574', ';.575', ';.576', ';.577', ';.578', ';.579', ';.580', ';.581', ';.582', ';.583', ';.584', ';.585', ';.586', ';.587', ';.588', ';.589', ';.590', ';.591', ';.592', ';.593', ';.594', ';.595', ';.596', ';.597', ';.598', ';.599', ';.600', ';.601', ';.602', ';.603', ';.604', ';.605', ';.606', ';.607', ';.608', ';.609', ';.610', ';.611', ';.612', ';.613', ';.614', ';.615', ';.616', ';.617', ';.618', ';.619', ';.620', ';.621', ';.622', ';.623', ';.624', ';.625', ';.626', ';.627', ';.628', ';.629', ';.630', ';.631', ';.632', ';.633', ';.634', ';.635', ';.636', ';.637', ';.638', ';.639', ';.640', ';.641', ';.642', ';.643', ';.644', ';.645', ';.646', ';.647', ';.648', ';.649', ';.650', ';.651', ';.652', ';.653', ';.654', ';.655', ';.656', ';.657', ';.658', ';.659', ';.660', ';.661', ';.662', ';.663', ';.664', ';.665', ';.666', ';.667', ';.668', ';.669', ';.670', ';.671', ';.672', ';.673', ';.674', ';.675', ';.676', ';.677', ';.678', ';.679', ';.680', ';.681', ';.682', ';.683', ';.684', ';.685', ';.686', ';.687', ';.688', ';.689', ';.690', ';.691', ';.692', ';.693', ';.694', ';.695', ';.696', ';.697', ';.698', ';.699', ';.700', ';.701', ';.702', ';.703', ';.704', ';.705', ';.706', ';.707', ';.708', ';.709', ';.710', ';.711', ';.712', ';.713', ';.714', ';.715', ';.716', ';.717', ';.718', ';.719', ';.720', ';.721', ';.722', ';.723', ';.724', ';.725', ';.726', ';.727', ';.728', ';.729', ';.730', ';.731', ';.732', ';.733', ';.734', ';.735', ';.736', ';.737', ';.738', ';.739', ';.740', ';.741', ';.742', ';.743', ';.744', ';.745', ';.746', ';.747', ';.748', ';.749', ';.750', ';.751', ';.752', ';.753', ';.754', ';.755', ';.756', ';.757', ';.758', ';.759', ';.760', ';.761', ';.762', ';.763', ';.764', ';.765', ';.766', ';.767', ';.768', ';.769', ';.770', ';.771', ';.772', ';.773', ';.774', ';.775', ';.776', ';.777', ';.778', ';.779', ';.780', ';.781', ';.782', ';.783', ';.784', ';.785', ';.786', ';.787', ';.788', ';.789', ';.790', ';.791', ';.792', ';.793', ';.794', ';.795', ';.796', ';.797', ';.798', ';.799', ';.800', ';.801', ';.802', ';.803', ';.804', ';.805', ';.806', ';.807', ';.808', ';.809', ';.810', ';.811', ';.812', ';.813', ';.814', ';.815', ';.816', ';.817', ';.818', ';.819', ';.820', ';.821', ';.822', ';.823', ';.824', ';.825', ';.826', ';.827', ';.828', ';.829', ';.830', ';.831', ';.832', ';.833', ';.834', ';.835', ';.836', ';.837', ';.838', ';.839', ';.840', ';.841', ';.842', ';.843', ';.844', ';.845', ';.846', ';.847', ';.848', ';.849', ';.850', ';.851', ';.852', ';.853', ';.854', ';.855', ';.856', ';.857', ';.858', ';.859', ';.860', ';.861', ';.862', ';.863', ';.864', ';.865', ';.866', ';.867', ';.868', ';.869', ';.870', ';.871', ';.872', ';.873', ';.874', ';.875', ';.876', ';.877', ';.878', ';.879', ';.880', ';.881', ';.882', ';.883', ';.884', ';.885', ';.886', ';.887', ';.888', ';.889', ';.890', ';.891', ';.892', ';.893', ';.894', ';.895', ';.896', ';.897', ';.898', ';.899', ';.900', ';.901', ';.902', ';.903', ';.904', ';.905', ';.906', ';.907', ';.908', ';.909', ';.910', ';.911', ';.912', ';.913', ';.914', ';.915', ';.916', ';.917', ';.918', ';.919', ';.920', ';.921', ';.922', ';.923', ';.924', ';.925', ';.926', ';.927', ';.928', ';.929', ';.930', ';.931', ';.932', ';.933', ';.934', ';.935', ';.936', ';.937', ';.938', ';.939', ';.940', ';.941', ';.942', ';.943', ';.944', ';.945', ';.946', ';.947', ';.948', ';.949', ';.950', ';.951', ';.952', ';.953', ';.954', ';.955', ';.956', ';.957', ';.958', ';.959', ';.960', ';.961', ';.962', ';.963', ';.964', ';.965', ';.966', ';.967', ';.968', ';.969', ';.970', ';.971', ';.972', ';.973', ';.974', ';.975', ';.976', ';.977', ';.978', ';.979', ';.980', ';.981', ';.982', ';.983', ';.984', ';.985', ';.986', ';.987', ';.988', ';.989', ';.990', ';.991', ';.992', ';.993', ';.994', ';.995', ';.996', ';.997', ';.998', ';.999', ';.1000', ';.1001', ';.1002', ';.1003', ';.1004', ';.1005', ';.1006', ';.1007', ';.1008', ';.1009', ';.1010', ';.1011', ';.1012', ';.1013', ';.1014', ';.1015', ';.1016', ';.1017', ';.1018', ';.1019', ';.1020', ';.1021', ';.1022', ';.1023', ';.1024', ';.1025', ';.1026', ';.1027', ';.1028', ';.1029', ';.1030', ';.1031', ';.1032', ';.1033', ';.1034', ';.1035', ';.1036', ';.1037', ';.1038', ';.1039', ';.1040', ';.1041', ';.1042', ';.1043', ';.1044', ';.1045', ';.1046', ';.1047', ';.1048', ';.1049', ';.1050', ';.1051', ';.1052', ';.1053', ';.1054', ';.1055', ';.1056', ';.1057', ';.1058', ';.1059', ';.1060', ';.1061', ';.1062', ';.1063', ';.1064', ';.1065', ';.1066', ';.1067', ';.1068', ';.1069', ';.1070', ';.1071', ';.1072', ';.1073', ';.1074', ';.1075', ';.1076', ';.1077', ';.1078', ';.1079', ';.1080', ';.1081', ';.1082', ';.1083', ';.1084', ';.1085', ';.1086', ';.1087', ';.1088', ';.1089', ';.1090', ';.1091', ';.1092', ';.1093', ';.1094', ';.1095', ';.1096', ';.1097', ';.1098', ';.1099', ';.1100', ';.1101', ';.1102', ';.1103', ';.1104', ';.1105', ';.1106', ';.1107', ';.1108', ';.1109', ';.1110', ';.1111', ';.1112', ';.1113', ';.1114', ';.1115', ';.1116', ';.1117', ';.1118', ';.1119', ';.1120', ';.1121', ';.1122', ';.1123', ';.1124', ';.1125', ';.1126', ';.1127', ';.1128', ';.1129', ';.1130', ';.1131', ';.1132', ';.1133', ';.1134', ';.1135', ';.1136', ';.1137', ';.1138', ';.1139', ';.1140', ';.1141', ';.1142', ';.1143', ';.1144', ';.1145', ';.1146', ';.1147', ';.1148', ';.1149', ';.1150', ';.1151', ';.1152', ';.1153', ';.1154', ';.1155', ';.1156', ';.1157', ';.1158', ';.1159', ';.1160', ';.1161', ';.1162', ';.1163', ';.1164', ';.1165', ';.1166', ';.1167', ';.1168', ';.1169', ';.1170', ';.1171', ';.1172', ';.1173', ';.1174', ';.1175', ';.1176', ';.1177', ';.1178', ';.1179', ';.1180', ';.1181', ';.1182', ';.1183', ';.1184', ';.1185', ';.1186', ';.1187', ';.1188', ';.1189', ';.1190', ';.1191', ';.1192', ';.1193', ';.1194', ';.1195', ';.1196', ';.1197', ';.1198', ';.1199', ';.1200', ';.1201', ';.1202', ';.1203', ';.1204', ';.1205', ';.1206', ';.1207', ';.1208', ';.1209', ';.1210', ';.1211', ';.1212', ';.1213', ';.1214', ';.1215', ';.1216', ';.1217', ';.1218', ';.1219', ';.1220', ';.1221', ';.1222', ';.1223', ';.1224', ';.1225', ';.1226', ';.1227', ';.1228', ';.1229', ';.1230', ';.1231', ';.1232', ';.1233', ';.1234', ';.1235', ';.1236', ';.1237', ';.1238', ';.1239', ';.1240', ';.1241', ';.1242', ';.1243', ';.1244', ';.1245', ';.1246', ';.1247', ';.1248', ';.1249', ';.1250', ';.1251', ';.1252', ';.1253', ';.1254', ';.1255', ';.1256', ';.1257', ';.1258', ';.1259', ';.1260', ';.1261', ';.1262', ';.1263', ';.1264', ';.1265', ';.1266', ';.1267', ';.1268', ';.1269', ';.1270', ';.1271', ';.1272', ';.1273', ';.1274', ';.1275', ';.1276', ';.1277', ';.1278', ';.1279', ';.1280', ';.1281', ';.1282', ';.1283', ';.1284', ';.1285', ';.1286', ';.1287', ';.1288', ';.1289', ';.1290', ';.1291', ';.1292', ';.1293', ';.1294', ';.1295', ';.1296', ';.1297', ';.1298', ';.1299', ';.1300', ';.1301', ';.1302', ';.1303', ';.1304', ';.1305', ';.1306', ';.1307', ';.1308', ';.1309', ';.1310', ';.1311', ';.1312', ';.1313', ';.1314', ';.1315', ';.1316', ';.1317', ';.1318', ';.1319', ';.1320', ';.1321', ';.1322', ';.1323', ';.1324', ';.1325', ';.1326', ';.1327', ';.1328', ';.1329', ';.1330', ';.1331', ';.1332', ';.1333', ';.1334', ';.1335', ';.1336', ';.1337', ';.1338', ';.1339', ';.1340', ';.1341', ';.1342', ';.1343', ';.1344', ';.1345', 'Unnamed: 1346']

-- df_rppa head --
     Protein Name Gene Name Antibody validation status Antibody Origin  \
0  14-3-3_epsilon     YWHAE           Use with Caution           Mouse
1          4E-BP1  EIF4EBP1                  Validated          Rabbit
2     4E-BP1_pS65  EIF4EBP1                  Validated          Rabbit
3  4E-BP1_pT37T46  EIF4EBP1                  Validated          Rabbit
4     4E-BP1_pT70  EIF4EBP1           Use with Caution          Rabbit

  Antibody Source (Company) Catalog Number
0                Santa Cruz        sc-2395
1                       CST           9452
2                       CST           9456
3                       CST           9459
4                       CST           9455

-- df_copy head --
                      ;             ;.1        ;.2        ;.3  \
0           Sample Set;           Type;  Cytoband;   q value;
1  All Samples (n=230);  Amplification;   14q13.3;  2.27e-26;
2  All Samples (n=230);  Amplification;   8q24.21;   1.7e-17;
3  All Samples (n=230);  Amplification;   5p15.33;  8.89e-16;
4  All Samples (n=230);  Amplification;     12q15;  2.78e-16;

                 ;.4                        ;.5                       ;.6  \
0  Residual q value;      Wide peak boundaries;  Number of genes in peak;
1          2.27e-26;   chr14:36854137-37023019;                        2;
2          1.88e-17;  chr8:129157821-129195260;                        0;
3          4.69e-14;      chr5:1288616-1300024;                        1;
4          7.42e-13;   chr12:69212011-69485451;                        2;

                            ;.7                                ;.8  \
0  Number of microRNAs in peak;  Top candidate genes in wide peak;
1                            0;                            NKX2-1;
2                            2;                                 -;
3                            0;                              TERT;
4                            0;                              MDM2;

                       ;.9  ... ;.1337 ;.1338 ;.1339 ;.1340 ;.1341 ;.1342  \
0  All genes in wide peak;  ...      ;      ;      ;      ;      ;      ;
1                  NKX2-1;  ...      ;      ;      ;      ;      ;      ;
2            hsa-mir-1208;  ...      ;      ;      ;      ;      ;      ;
3                    TERT;  ...      ;      ;      ;      ;      ;      ;
4                     CPM;  ...      ;      ;      ;      ;      ;      ;

  ;.1343 ;.1344 ;.1345 Unnamed: 1346
0      ;      ;      ;           NaN
1      ;      ;      ;           NaN
2      ;      ;      ;           NaN
3      ;      ;      ;           NaN
4      ;      ;      ;           NaN

[5 rows x 1347 columns]

Merge operations halted due to missing 'Tumor ID' in some dataframes and potential loading issues with df_copy.
Please provide more information on the structure of S_Table_13_RPPA.xlsx and S_Table_6_Copy_Number.xlsx
and how they are intended to be joined with the clinical data.

In [ ]:
# Inspection brute des fichiers pour trouver les Tumor IDs
import pandas as pd

print("--- Inspection de S_Table_13_RPPA.xlsx (5 premières lignes) ---")
df_rppa_raw = pd.read_excel(f"{path}/S_Table_13_RPPA.xlsx", header=None, nrows=5)
display(df_rppa_raw)

print("\n--- Inspection de S_Table_6_Copy_Number.xlsx (5 premières lignes) ---")
df_copy_raw = pd.read_excel(f"{path}/S_Table_6_Copy_Number.xlsx", header=None, nrows=5)
display(df_copy_raw)

--- Inspection de S_Table_13_RPPA.xlsx (5 premières lignes) ---

,0,1,2,3,4,5
0,Supplementary Table 13: Validated Antibodies ...,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
1,Protein Name,Gene Name,Antibody validation status,Antibody Origin,Antibody Source (Company),Catalog Number
2,14-3-3_epsilon,YWHAE,Use with Caution,Mouse,Santa Cruz,sc-2395
3,4E-BP1,EIF4EBP1,Validated,Rabbit,CST,9452
4,4E-BP1_pS65,EIF4EBP1,Validated,Rabbit,CST,9456

--- Inspection de S_Table_6_Copy_Number.xlsx (5 premières lignes) ---

,0,1,2,3,4,5,6,7,8,9,...,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346
0,Supplementary Table 6. Recurrent copy number a...,Unnamed: 1;,Unnamed: 2;,Unnamed: 3;,Unnamed: 4;,Unnamed: 5;,Unnamed: 6;,Unnamed: 7;,Unnamed: 8;,Unnamed: 9;,...,Unnamed: 1337;,Unnamed: 1338;,Unnamed: 1339;,Unnamed: 1340;,Unnamed: 1341;,Unnamed: 1342;,Unnamed: 1343;,Unnamed: 1344;,Unnamed: 1345;,Unnamed: 1346
1,;,;,;,;,;,;,;,;,;,;,...,;,;,;,;,;,;,;,;,;,NaN
2,Sample Set;,Type;,Cytoband;,q value;,Residual q value;,Wide peak boundaries;,Number of genes in peak;,Number of microRNAs in peak;,Top candidate genes in wide peak;,All genes in wide peak;,...,;,;,;,;,;,;,;,;,;,NaN
3,All Samples (n=230);,Amplification;,14q13.3;,2.27e-26;,2.27e-26;,chr14:36854137-37023019;,2;,0;,NKX2-1;,NKX2-1;,...,;,;,;,;,;,;,;,;,;,NaN
4,All Samples (n=230);,Amplification;,8q24.21;,1.7e-17;,1.88e-17;,chr8:129157821-129195260;,0;,2;,-;,hsa-mir-1208;,...,;,;,;,;,;,;,;,;,;,NaN

In [ ]:
import pandas as pd

def inspect_excel_sheets(file_path):
    print(f"\n--- Inspection des onglets de : {os.path.basename(file_path)} ---")
    try:
        xl = pd.ExcelFile(file_path)
        sheets = xl.sheet_names
        print(f"Onglets trouvés : {sheets}")
        for sheet in sheets:
            print(f"\nAperçu de l'onglet : {sheet}")
            df = pd.read_excel(file_path, sheet_name=sheet, nrows=5)
            display(df.head())
    except Exception as e:
        print(f"Erreur lors de la lecture : {e}")

# Inspection des deux fichiers problématiques
inspect_excel_sheets(f"{path}/S_Table_13_RPPA.xlsx")
inspect_excel_sheets(f"{path}/S_Table_6_Copy_Number.xlsx")

--- Inspection des onglets de : S_Table_13_RPPA.xlsx ---
Onglets trouvés : ['S_Table_13_RPPA']

Aperçu de l'onglet : S_Table_13_RPPA

,Supplementary Table 13: Validated Antibodies used in reverse phase protein arrays,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Protein Name,Gene Name,Antibody validation status,Antibody Origin,Antibody Source (Company),Catalog Number
1,14-3-3_epsilon,YWHAE,Use with Caution,Mouse,Santa Cruz,sc-2395
2,4E-BP1,EIF4EBP1,Validated,Rabbit,CST,9452
3,4E-BP1_pS65,EIF4EBP1,Validated,Rabbit,CST,9456
4,4E-BP1_pT37T46,EIF4EBP1,Validated,Rabbit,CST,9459

--- Inspection des onglets de : S_Table_6_Copy_Number.xlsx ---
Onglets trouvés : ['S_Table_6_Copy_Number']

Aperçu de l'onglet : S_Table_6_Copy_Number

,Supplementary Table 6. Recurrent copy number alterations identified by GISTIC analysis of TCGA samples.;,Unnamed: 1;,Unnamed: 2;,Unnamed: 3;,Unnamed: 4;,Unnamed: 5;,Unnamed: 6;,Unnamed: 7;,Unnamed: 8;,Unnamed: 9;,...,Unnamed: 1337;,Unnamed: 1338;,Unnamed: 1339;,Unnamed: 1340;,Unnamed: 1341;,Unnamed: 1342;,Unnamed: 1343;,Unnamed: 1344;,Unnamed: 1345;,Unnamed: 1346
0,;,;,;,;,;,;,;,;,;,;,...,;,;,;,;,;,;,;,;,;,NaN
1,Sample Set;,Type;,Cytoband;,q value;,Residual q value;,Wide peak boundaries;,Number of genes in peak;,Number of microRNAs in peak;,Top candidate genes in wide peak;,All genes in wide peak;,...,;,;,;,;,;,;,;,;,;,NaN
2,All Samples (n=230);,Amplification;,14q13.3;,2.27e-26;,2.27e-26;,chr14:36854137-37023019;,2;,0;,NKX2-1;,NKX2-1;,...,;,;,;,;,;,;,;,;,;,NaN
3,All Samples (n=230);,Amplification;,8q24.21;,1.7e-17;,1.88e-17;,chr8:129157821-129195260;,0;,2;,-;,hsa-mir-1208;,...,;,;,;,;,;,;,;,;,;,NaN
4,All Samples (n=230);,Amplification;,5p15.33;,8.89e-16;,4.69e-14;,chr5:1288616-1300024;,1;,0;,TERT;,TERT;,...,;,;,;,;,;,;,;,;,;,NaN

In [ ]:
import pandas as pd
from google.colab import drive
import os

# 1. Montage du Drive
drive.mount('/content/drive')

# 2. Définition du chemin REEL (corrigé)
path = "/content/drive/MyDrive/pfe_digital_twin"

# 3. Chargement des fichiers (Utilisation de read_excel car ce sont des .xlsx)
try:
    # On charge le fichier clinique principal
    df_clinical = pd.read_excel(f"{path}/EGFR_Mutations_Table7_Cleaned.xlsx")

    # On charge le fichier RPPA (On utilise la table 13 pour l'instant)
    df_rppa = pd.read_excel(f"{path}/S_Table_13_RPPA.xlsx", header=1)

    # 4. Nettoyage des noms de colonnes
    df_clinical.columns = df_clinical.columns.str.strip()
    df_rppa.columns = df_rppa.columns.str.strip()

    # 5. Préparation de la fusion
    # Note: On utilise 'Tumor ID' qui est présent dans ton fichier clinique
    # Si df_rppa n'a pas de 'Tumor ID', la fusion retournera 0 lignes
    if 'Tumor ID' in df_rppa.columns:
        master_twin = pd.merge(df_clinical, df_rppa, on='Tumor ID', how='inner')
    else:
        print("⚠️ Attention: 'Tumor ID' absent de la table RPPA. Fusion impossible en l'état.")
        master_twin = df_clinical # On garde au moins les données cliniques

    # 6. Sauvegarde finale
    output_file = f"{path}/Master_Twin_Data_Final.csv"
    master_twin.to_csv(output_file, index=False)

    print(f"✅ Terminé ! Le fichier a été sauvegardé ici : {output_file}")
    print(f"Nombre de patients : {master_twin.shape[0]}")

except FileNotFoundError as e:
    print(f"❌ Erreur : Fichier introuvable. Vérifie le chemin : {e}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
⚠️ Attention: 'Tumor ID' absent de la table RPPA. Fusion impossible en l'état.
✅ Terminé ! Le fichier a été sauvegardé ici : /content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv
Nombre de patients : 33

In [ ]:
import os
path = '/content/drive/MyDrive/pfe_digital_twin'
if os.path.exists(path):
    files = os.listdir(path)
    print(f'Fichiers trouves dans {path} :\n')
    for f in sorted(files):
        print(f'- {f}')
else:
    print(f"Erreur : Le chemin {path} n'existe pas.")

Fichiers trouves dans /content/drive/MyDrive/pfe_digital_twin :

- EGFR_Mutations_Table7_Cleaned.xlsx
- Master_Twin_Data_Final.csv
- S_Table_13_RPPA.xlsx
- S_Table_6_Copy_Number.xlsx
- gdc_manifest.2026-04-15.002227.txt
- pfe_digital_twin

In [ ]:
import pandas as pd
import os
from google.colab import drive

# 1. Montage
drive.mount('/content/drive')

# 2. Chemins
base_path = "/content/drive/MyDrive/pfe_digital_twin"

# 3. Chargement
df_rppa = pd.read_csv("/content/data_rppa.txt", sep='\t')
df_egfr = pd.read_excel(f"{base_path}/EGFR_Mutations_Table7_Cleaned.xlsx")

# 4. Transposition du RPPA
gene_col = df_rppa.columns[0]
df_rppa = df_rppa.set_index(gene_col).T.reset_index().rename(columns={'index': 'Tumor ID'})

# 5. Harmonisation des IDs (Crucial !)
# On transforme 'TCGA-05-4382-01' en 'TCGA-05-4382' pour correspondre au fichier clinique
df_egfr['Tumor ID'] = df_egfr['Tumor ID'].str.strip().str[:12]
df_rppa['Tumor ID'] = df_rppa['Tumor ID'].str.strip().str[:12]

# 6. Fusion
master = pd.merge(df_egfr, df_rppa, on='Tumor ID', how='inner')

# 7. Sauvegarde
output_path = f"{base_path}/Master_Twin_Data_Final.csv"
master.to_csv(output_path, index=False)

print(f"✅ Fusion réussie : {master.shape[0]} patients identifiés.")
print(f"Fichier sauvegardé : {output_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Fusion réussie : 27 patients identifiés.
Fichier sauvegardé : /content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv

In [ ]:
import shutil

# Copie des fichiers vers le Drive pour ne plus jamais les perdre
shutil.copy("/content/data_rppa.txt", "/content/drive/MyDrive/pfe_digital_twin/")
shutil.copy("/content/data_cna.txt", "/content/drive/MyDrive/pfe_digital_twin/")

print("✅ Fichiers sécurisés dans le Drive.")

✅ Fichiers sécurisés dans le Drive.

In [ ]:
import pandas as pd

# 1. Chargement du fichier Master existant (Clinique + RPPA)
path = "/content/drive/MyDrive/pfe_digital_twin"
master_rppa = pd.read_csv(f"{path}/Master_Twin_Data_Final.csv")

# 2. Chargement et préparation des données CNA
df_cna_raw = pd.read_csv("/content/data_cna.txt", sep='\t')

# Transposition : les gènes (Hugo_Symbol) deviennent des colonnes, les patients des lignes
# On ignore la colonne 'Entrez_Gene_Id' pour la transposition
df_cna = df_cna_raw.drop(columns=['Entrez_Gene_Id']).set_index('Hugo_Symbol').T.reset_index()
df_cna = df_cna.rename(columns={'index': 'Tumor ID'})

# 3. Harmonisation des IDs à 12 caractères
master_rppa['Tumor ID'] = master_rppa['Tumor ID'].str.strip().str[:12]
df_cna['Tumor ID'] = df_cna['Tumor ID'].str.strip().str[:12]

# 4. Fusion finale (Multi-Omique)
# On utilise 'inner' pour garder uniquement les patients ayant toutes les données
master_multi = pd.merge(master_rppa, df_cna, on='Tumor ID', how='inner')

# 5. Sauvegarde
output_multi = f"{path}/Master_MultiOmics_27.csv"
master_multi.to_csv(output_multi, index=False)

print(f"✅ Fusion Multi-Omique réussie !")
print(f"Nombre final de patients : {master_multi.shape[0]}")
print(f"Nombre total de colonnes (Clinique + Protéines + CNA) : {master_multi.shape[1]}")
print(f"Fichier sauvegardé : {output_multi}")

display(master_multi.head())

✅ Fusion Multi-Omique réussie !
Nombre final de patients : 27
Nombre total de colonnes (Clinique + Protéines + CNA) : 23686
Fichier sauvegardé : /content/drive/MyDrive/pfe_digital_twin/Master_MultiOmics_27.csv

,Tumor ID,Sex,Age at diagnosis,T stage,N stage,Tumor stage,Smoking Status,Survival,Transversion High/Low,Nonsilent Mutations,...,MIR452,MIR105-1,MIR105-2,MIR767,MIR3202-1,MIR3202-2,MIR718,MIR1184-1,MIR1184-2,MIR1184-3
0,TCGA-05-4402,FEMALE,57,T2,NX,Stage IV,Lifelong Non-smoker,DECEASED,Low,145,...,0,0,0,0,0,0,0,0,0,0
1,TCGA-05-4410,MALE,62,T2,N0,Stage IB,Current reformed smoker for < or = 15 years,LIVING,High,990,...,0,0,0,0,0,0,0,0,0,0
2,TCGA-05-5423,MALE,65,T2,N1,Stage IIB,Current reformed smoker for > 15 years,LIVING,High,136,...,1,1,1,1,1,1,1,1,1,1
3,TCGA-38-4627,FEMALE,64,T1b,N1,Stage IIA,Current reformed smoker for < or = 15 years,DECEASED,Low,33,...,0,0,0,0,0,0,0,0,0,0
4,TCGA-38-6178,FEMALE,70,T2b,N2,Stage IIIA,Lifelong Non-smoker,LIVING,Low,64,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import pandas as pd
import os

# 1. Configuration des chemins
path = "/content/drive/MyDrive/pfe_digital_twin"
master_path = f"{path}/Master_Twin_Data_Final.csv"
cna_file = "/content/data_cna.txt"

# 2. Chargement des données
df_master = pd.read_csv(master_path)
df_cna_raw = pd.read_csv(cna_file, sep='\t')

# 3. Préparation du CNA (Transposition)
# On retire Entrez_Gene_Id, on met Hugo_Symbol en index, puis on transpose
df_cna = df_cna_raw.drop(columns=['Entrez_Gene_Id']).set_index('Hugo_Symbol').T.reset_index()
df_cna = df_cna.rename(columns={'index': 'Tumor ID'})

# 4. Harmonisation des IDs (Troncature à 12 caractères)
df_master['Tumor ID'] = df_master['Tumor ID'].str.strip().str[:12]
df_cna['Tumor ID'] = df_cna['Tumor ID'].str.strip().str[:12]

# 5. Fusion Multi-Omique (Clinique + RPPA + CNA)
master_multi = pd.merge(df_master, df_cna, on='Tumor ID', how='inner')

# 6. Sauvegarde du fichier final
output_multi = f"{path}/Master_MultiOmics_27.csv"
master_multi.to_csv(output_multi, index=False)

print(f"✅ Fusion Multi-Omique terminée avec succès !")
print(f"📊 Nombre de patients : {master_multi.shape[0]}")
print(f"🧬 Nombre total de variables (colonnes) : {master_multi.shape[1]}")
print(f"💾 Fichier sauvegardé : {output_multi}")

display(master_multi.head())

✅ Fusion Multi-Omique terminée avec succès !
📊 Nombre de patients : 27
🧬 Nombre total de variables (colonnes) : 23686
💾 Fichier sauvegardé : /content/drive/MyDrive/pfe_digital_twin/Master_MultiOmics_27.csv

,Tumor ID,Sex,Age at diagnosis,T stage,N stage,Tumor stage,Smoking Status,Survival,Transversion High/Low,Nonsilent Mutations,...,MIR452,MIR105-1,MIR105-2,MIR767,MIR3202-1,MIR3202-2,MIR718,MIR1184-1,MIR1184-2,MIR1184-3
0,TCGA-05-4402,FEMALE,57,T2,NX,Stage IV,Lifelong Non-smoker,DECEASED,Low,145,...,0,0,0,0,0,0,0,0,0,0
1,TCGA-05-4410,MALE,62,T2,N0,Stage IB,Current reformed smoker for < or = 15 years,LIVING,High,990,...,0,0,0,0,0,0,0,0,0,0
2,TCGA-05-5423,MALE,65,T2,N1,Stage IIB,Current reformed smoker for > 15 years,LIVING,High,136,...,1,1,1,1,1,1,1,1,1,1
3,TCGA-38-4627,FEMALE,64,T1b,N1,Stage IIA,Current reformed smoker for < or = 15 years,DECEASED,Low,33,...,0,0,0,0,0,0,0,0,0,0
4,TCGA-38-6178,FEMALE,70,T2b,N2,Stage IIIA,Lifelong Non-smoker,LIVING,Low,64,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# 1. Installation de l'outil GDC-Client
!wget https://gdc.cancer.gov/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip
!unzip gdc-client_v1.6.1_Ubuntu_x64.zip

# Assurez-vous que l'exécutable gdc-client a les bonnes permissions
!chmod +x ./gdc-client

# 2. Montage du Drive
from google.colab import drive
drive.mount('/content/drive')

# 3. Paramètres (Vérifiez bien le nom de votre fichier manifest)
manifest_path = "/content/drive/MyDrive/pfe_digital_twin/gdc_manifest.2026-04-15.002227.txt"
output_dir = "/content/drive/MyDrive/pfe_digital_twin/lames_svs"

# 4. Créer le répertoire de sortie s'il n'existe pas
import os
os.makedirs(output_dir, exist_ok=True)

# 5. Lancement du téléchargement
# On utilise --retry-amount 5 au cas où la connexion saute
!./gdc-client download -m {manifest_path} -d {output_dir} --retry-amount 5

--2026-04-15 01:51:24--  https://gdc.cancer.gov/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip
Resolving gdc.cancer.gov (gdc.cancer.gov)... 44.213.225.57, 52.21.56.78
Connecting to gdc.cancer.gov (gdc.cancer.gov)|44.213.225.57|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://gdc.cancer.gov:443/system/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip [following]
--2026-04-15 01:51:24--  https://gdc.cancer.gov/system/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip
Reusing existing connection to gdc.cancer.gov:443.
HTTP request sent, awaiting response... 200 OK
Length: 23940006 (23M) [application/zip]
Saving to: ‘gdc-client_v1.6.1_Ubuntu_x64.zip.2’

gdc-client_v1.6.1_U 100%[===================>]  22.83M  64.0MB/s    in 0.4s

2026-04-15 01:51:25 (64.0 MB/s) - ‘gdc-client_v1.6.1_Ubuntu_x64.zip.2’ saved [23940006/23940006]

Archive:  gdc-client_v1.6.1_Ubuntu_x64.zip
replace gdc-client? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
 extracting: gdc-client
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
100% [#############################################] Time:  0:00:27  26.3 MiB/s
  2% [#                                            ] ETA:   0:00:55  15.6 MiB/s Traceback (most recent call last):
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/segment.py", line 368, in wait_for_completion
  File "<string>", line 2, in get
  File "multiprocessing/managers.py", line 819, in _callmethod
  File "multiprocessing/connection.py", line 250, in recv
  File "multiprocessing/connection.py", line 407, in _recv_bytes
  File "multiprocessing/connection.py", line 379, in _recv
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gdc-client", line 103, in <module>
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/download/parser.py", line 115, in download
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/client.py", line 143, in download_files
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/download/client.py", line 315, in parallel_download
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/client.py", line 177, in parallel_download
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/client.py", line 238, in _download
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/segment.py", line 390, in wait_for_completion
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/segment.py", line 349, in finish_download
  File "<string>", line 2, in put
  File "multiprocessing/managers.py", line 818, in _callmethod
  File "multiprocessing/connection.py", line 206, in send
  File "multiprocessing/connection.py", line 404, in _send_bytes
  File "multiprocessing/connection.py", line 368, in _send
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gdc-client", line 109, in <module>
  File "logging/__init__.py", line 1390, in warning
  File "logging/__init__.py", line 1513, in _log
  File "logging/__init__.py", line 1482, in makeRecord
KeyboardInterrupt
[29954] Failed to execute script gdc-client
ERROR: Process stopped by user.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "multiprocessing/popen_fork.py", line 28, in poll
KeyboardInterrupt
ERROR: Process stopped by user.
Process Process-6:
Traceback (most recent call last):
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/client.py", line 215, in download_worker
  File "<string>", line 2, in put
  File "multiprocessing/managers.py", line 818, in _callmethod
  File "multiprocessing/connection.py", line 206, in send
  File "multiprocessing/connection.py", line 404, in _send_bytes
  File "multiprocessing/connection.py", line 368, in _send
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/client.py", line 219, in download_worker
  File "<string>", line 2, in put
  File "multiprocessing/managers.py", line 818, in _callmethod
  File "multiprocessing/connection.py", line 206, in send
  File "multiprocessing/connection.py", line 404, in _send_bytes
  File "multiprocessing/connection.py", line 368, in _send
BrokenPipeError: [Errno 32] Broken pipe
Process Process-5:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "gdc_client-1.6.1-py3.7.egg/gdc_client/parcel/client.py", line 212, in download_worker
KeyboardInterrupt
^C

In [ ]:
# Remplace l'ID par celui que tu as copié
id_unique = "16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a	"

!./gdc-client download {id_unique} -d /content/drive/MyDrive/pfe_digital_twin/lames_svs

ERROR: 16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a: 404 Client Error: NOT FOUND for url: https://api.gdc.cancer.gov/data/16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a: {"message":"16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a not found"}

ERROR: 16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a: 404 Client Error: NOT FOUND for url: https://api.gdc.cancer.gov/data/16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a: {"message":"16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a not found"}

ERROR: Unable to download file https://api.gdc.cancer.gov/data/16cac4fe-54cf-4c33-a8c9-11d528886e4f017b6ede405f36dca5e09d503bd0048a
Successfully downloaded: 0
Failed downloads: 1

In [ ]:
# Exemple avec un vrai ID (remplace par le tien si besoin)
file_uuid = "16cac4fe-54cf-4c33-a8c9-11d528886e4f" # <--- Vérifie bien le format !

!./gdc-client download {file_uuid} -d /content/drive/MyDrive/pfe_digital_twin/lames_svs

100% [#############################################] Time:  0:00:06  21.3 MiB/s
Successfully downloaded: 1

In [ ]:
import shutil
shutil.copy("/content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv", "/content/drive/MyDrive/pfe_digital_twin/")

SameFileError: '/content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv' and '/content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv' are the same file

In [ ]:
import os

file_path = "/content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv"

if os.path.exists(file_path):
    print(f"✅ Le fichier est accessible : {file_path}")
    df_check = pd.read_csv(file_path)
    print(f"Aperçu des données ({df_check.shape[0]} lignes) :")
    display(df_check.head())
else:
    print(f"❌ Le fichier est introuvable au chemin : {file_path}")

✅ Le fichier est accessible : /content/drive/MyDrive/pfe_digital_twin/Master_Twin_Data_Final.csv
Aperçu des données (27 lignes) :

,Tumor ID,Sex,Age at diagnosis,T stage,N stage,Tumor stage,Smoking Status,Survival,Transversion High/Low,Nonsilent Mutations,...,C12ORF5|TIGAR-R-V,TGM2|Transglutaminase-M-V,TTF1|TTF1-R-V,TSC2|Tuberin-R-C,KDR|VEGFR2-R-V,XBP1|XBP1-G-C,XRCC1|XRCC1-R-C,YAP1|YAP_pS127-R-C,YBX1|YB-1-R-V,YBX1|YB-1_pS102-R-V
0,TCGA-05-4402,FEMALE,57,T2,NX,Stage IV,Lifelong Non-smoker,DECEASED,Low,145,...,0.029194,0.463065,-0.999534,3.053097,-2.774968,-1.515606,-0.487095,1.498959,-0.732527,0.469782
1,TCGA-05-4410,MALE,62,T2,N0,Stage IB,Current reformed smoker for < or = 15 years,LIVING,High,990,...,0.530956,0.700753,-1.033972,3.511528,-2.769518,-1.324818,-0.129875,1.834562,-1.416172,0.756826
2,TCGA-05-5423,MALE,65,T2,N1,Stage IIB,Current reformed smoker for > 15 years,LIVING,High,136,...,1.319412,0.645193,-0.775034,4.206203,-2.320367,-1.070525,1.623134,1.289592,-1.439702,1.272472
3,TCGA-38-4627,FEMALE,64,T1b,N1,Stage IIA,Current reformed smoker for < or = 15 years,DECEASED,Low,33,...,0.209378,0.870801,-1.072369,1.021267,-2.914913,-1.651101,-0.272588,-0.479534,-1.677446,1.054796
4,TCGA-38-6178,FEMALE,70,T2b,N2,Stage IIIA,Lifelong Non-smoker,LIVING,Low,64,...,0.468208,0.432144,-1.091412,2.897810,-2.963398,-1.548816,0.565732,1.661089,-1.477667,0.772332